# Stage 1 Download the dependencies
FROM eclipse-temurin:21-jdk-alpine AS dependencies

RUN apk add --no-cache maven

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline 

# Stage 2 Build the application

FROM dependencies AS builder

COPY src ./src

RUN mvn package -DskipTests

# Stage 3 Run the application

FROM eclipse-temurin:21-jre-alpine AS runtime

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget -qO- http://localhost:8080/actuator/health || exit 1

ENTRYPOINT ["java", "-jar", "app.jar"]